In [2]:
import numpy as np
import seaborn as sns
import uproot

In [3]:
file = uproot.open("ttbar+2j_dilepton.root")

In [4]:
file.keys()

[b'ProcessID0;1', b'Delphes;1']

In [5]:
tree = file["Delphes"]

In [6]:
tree.keys()

[b'Event',
 b'Event_size',
 b'Weight',
 b'Weight_size',
 b'Particle',
 b'Particle_size',
 b'Track',
 b'Track_size',
 b'Tower',
 b'Tower_size',
 b'EFlowTrack',
 b'EFlowTrack_size',
 b'EFlowPhoton',
 b'EFlowPhoton_size',
 b'EFlowNeutralHadron',
 b'EFlowNeutralHadron_size',
 b'GenJet',
 b'GenJet_size',
 b'GenMissingET',
 b'GenMissingET_size',
 b'Jet',
 b'Jet_size',
 b'Electron',
 b'Electron_size',
 b'Photon',
 b'Photon_size',
 b'Muon',
 b'Muon_size',
 b'FatJet',
 b'FatJet_size',
 b'MissingET',
 b'MissingET_size',
 b'ScalarHT',
 b'ScalarHT_size']

In [20]:
tree.show()


Event                      TStreamerInfo              asdtype('>i4')
Event.fUniqueID            TStreamerBasicType         asjagged(asdtype('>u4'))
Event.fBits                TStreamerBasicType         asjagged(asdtype('>u4'))
Event.Number               TStreamerBasicType         asjagged(asdtype('>i8'))
Event.ReadTime             TStreamerBasicType         asjagged(asdtype('>f4'))
Event.ProcTime             TStreamerBasicType         asjagged(asdtype('>f4'))
Event.ProcessID            TStreamerBasicType         asjagged(asdtype('>i4'))
Event.MPI                  TStreamerBasicType         asjagged(asdtype('>i4'))
Event.Weight               TStreamerBasicType         asjagged(asdtype('>f4'))
Event.CrossSection         TStreamerBasicType         asjagged(asdtype('>f4'))
Event.CrossSectionError    TStreamerBasicType         asjagged(asdtype('>f4'))
Event.Scale                TStreamerBasicType         asjagged(asdtype('>f4'))
Event.AlphaQED             TStreamerBasicType         asjagged

In [21]:
tree.name, tree.title, tree.numentries


(b'Delphes', b'Analysis tree', 1000)

In [17]:
all_ttrees = dict(file.allitems(filterclass=lambda cls: issubclass(cls, uproot.tree.TTreeMethods)))
all_ttrees

{b'Delphes;1': <TTree b'Delphes' at 0x001cdcf5b780>}

In [53]:
Eflow=tree.array("EFlowNeutralHadron")
Eflow

array([ 38,  63,  60,  50,  56,  22,  50,  29,  52,  19,  61,  28,  33,
        45,  63,  23,  23, 107,  45, 111,  28,  37,  62,  25,  41,  43,
        29,  18,  16,  19,  47,  35, 115,  25,  62,  40,  35, 114,  35,
        25,  40,  68,  17,  69,  31,  85,  89,  38,  67,  42,  65,  40,
        97,  76,  26,  63,  26,  58,  30,  49,  51,  21,  48,  77,  32,
        22,  22,  54,  62,  72,  32,  89,  13,  26,  22,  32,  55,  43,
        83,  33,  23,  42,  79,  41,  52,  32,  44,  43,  41,  48,  15,
        61,  50,  51,  58,  63,  56,  47,  38,  67,  49,  11,  20,  76,
        61,  56,  57,  36,  67,  22,  50,  64,  32,  16,  51,  36,  21,
        43,  75,  67,  51,  65,  39,  22,  26,  42,  51,  67,  36,  40,
        52,  67,  20,  56,  47,  28,  37,  59,  25,  45,  94,  37,  32,
       103,  62,  29,  36,  30,  34,  95,  36,  54,  53,  37,  34,  63,
        30,  38,  20,  47,  28,  66,  62,  62,  39,  31,  18,  78,  81,
        58,  52,  54,  25,  63,  79,  14,  28,  38,  75,  80,  8

In [55]:
Eflowsize=tree.array("EFlowNeutralHadron_size")
Eflowsize

array([ 38,  63,  60,  50,  56,  22,  50,  29,  52,  19,  61,  28,  33,
        45,  63,  23,  23, 107,  45, 111,  28,  37,  62,  25,  41,  43,
        29,  18,  16,  19,  47,  35, 115,  25,  62,  40,  35, 114,  35,
        25,  40,  68,  17,  69,  31,  85,  89,  38,  67,  42,  65,  40,
        97,  76,  26,  63,  26,  58,  30,  49,  51,  21,  48,  77,  32,
        22,  22,  54,  62,  72,  32,  89,  13,  26,  22,  32,  55,  43,
        83,  33,  23,  42,  79,  41,  52,  32,  44,  43,  41,  48,  15,
        61,  50,  51,  58,  63,  56,  47,  38,  67,  49,  11,  20,  76,
        61,  56,  57,  36,  67,  22,  50,  64,  32,  16,  51,  36,  21,
        43,  75,  67,  51,  65,  39,  22,  26,  42,  51,  67,  36,  40,
        52,  67,  20,  56,  47,  28,  37,  59,  25,  45,  94,  37,  32,
       103,  62,  29,  36,  30,  34,  95,  36,  54,  53,  37,  34,  63,
        30,  38,  20,  47,  28,  66,  62,  62,  39,  31,  18,  78,  81,
        58,  52,  54,  25,  63,  79,  14,  28,  38,  75,  80,  8

In [29]:
E = tree.arrays(["EFlowNeutralHadron","EFlowNeutralHadron_size"])
E

{b'EFlowNeutralHadron': array([ 38,  63,  60,  50,  56,  22,  50,  29,  52,  19,  61,  28,  33,
         45,  63,  23,  23, 107,  45, 111,  28,  37,  62,  25,  41,  43,
         29,  18,  16,  19,  47,  35, 115,  25,  62,  40,  35, 114,  35,
         25,  40,  68,  17,  69,  31,  85,  89,  38,  67,  42,  65,  40,
         97,  76,  26,  63,  26,  58,  30,  49,  51,  21,  48,  77,  32,
         22,  22,  54,  62,  72,  32,  89,  13,  26,  22,  32,  55,  43,
         83,  33,  23,  42,  79,  41,  52,  32,  44,  43,  41,  48,  15,
         61,  50,  51,  58,  63,  56,  47,  38,  67,  49,  11,  20,  76,
         61,  56,  57,  36,  67,  22,  50,  64,  32,  16,  51,  36,  21,
         43,  75,  67,  51,  65,  39,  22,  26,  42,  51,  67,  36,  40,
         52,  67,  20,  56,  47,  28,  37,  59,  25,  45,  94,  37,  32,
        103,  62,  29,  36,  30,  34,  95,  36,  54,  53,  37,  34,  63,
         30,  38,  20,  47,  28,  66,  62,  62,  39,  31,  18,  78,  81,
         58,  52,  54,  25, 

In [44]:
data = tree.lazyarrays("*")
data

<Table [<Row 0> <Row 1> <Row 2> ... <Row 997> <Row 998> <Row 999>] at 0x001cdd4b89e8>

In [46]:
data = tree.lazyarrays(entrysteps=500)   # chunks of 500 events each
dataE1 = data["EFlowNeutralHadron"]
dataE1

##first and last chunks of the array can be read

<ChunkedArray [38 63 60 ... 59 27 63] at 0x001cdcbe6748>

In [47]:
[chunk.ismaterialized for chunk in dataE1.chunks]


[True, True]

In [48]:
##ufuncs - numpy
numpy.log(dataE1)


<ChunkedArray [3.6375861597263857 4.143134726391533 4.0943445622221 3.912023005428146 4.02535169073515 3.091042453358316 3.912023005428146 ...] at 0x001cdd2dbf28>

In [49]:
[chunk.ismaterialized for chunk in dataE1.chunks]

##all of the chunks have been read

[True, True]

In [50]:
numpy.array(dataE1)


array([ 38,  63,  60,  50,  56,  22,  50,  29,  52,  19,  61,  28,  33,
        45,  63,  23,  23, 107,  45, 111,  28,  37,  62,  25,  41,  43,
        29,  18,  16,  19,  47,  35, 115,  25,  62,  40,  35, 114,  35,
        25,  40,  68,  17,  69,  31,  85,  89,  38,  67,  42,  65,  40,
        97,  76,  26,  63,  26,  58,  30,  49,  51,  21,  48,  77,  32,
        22,  22,  54,  62,  72,  32,  89,  13,  26,  22,  32,  55,  43,
        83,  33,  23,  42,  79,  41,  52,  32,  44,  43,  41,  48,  15,
        61,  50,  51,  58,  63,  56,  47,  38,  67,  49,  11,  20,  76,
        61,  56,  57,  36,  67,  22,  50,  64,  32,  16,  51,  36,  21,
        43,  75,  67,  51,  65,  39,  22,  26,  42,  51,  67,  36,  40,
        52,  67,  20,  56,  47,  28,  37,  59,  25,  45,  94,  37,  32,
       103,  62,  29,  36,  30,  34,  95,  36,  54,  53,  37,  34,  63,
        30,  38,  20,  47,  28,  66,  62,  62,  39,  31,  18,  78,  81,
        58,  52,  54,  25,  63,  79,  14,  28,  38,  75,  80,  8

In [60]:
dict(file.classes())

{b'ProcessID0;1': uproot.rootio.TProcessID, b'Delphes;1': uproot.rootio.TTree}

In [62]:
processid = file["ProcessID0"]
processid

<TProcessID b'ProcessID0' at 0x001cd8736860>

In [63]:
processid._members()


['fName', 'fTitle']

In [64]:
processid._fName, processid._fTitle 

(b'ProcessID0', b'163729a6-3c51-11ea-ae04-0101007fbeef')

In [84]:
import pkgutil
file["Delphes"].values



<bound method TTreeMethods.values of <TTree b'Delphes' at 0x001cdd4018d0>>

In [85]:
file["Delphes"].show()


Event                      TStreamerInfo              asdtype('>i4')
Event.fUniqueID            TStreamerBasicType         asjagged(asdtype('>u4'))
Event.fBits                TStreamerBasicType         asjagged(asdtype('>u4'))
Event.Number               TStreamerBasicType         asjagged(asdtype('>i8'))
Event.ReadTime             TStreamerBasicType         asjagged(asdtype('>f4'))
Event.ProcTime             TStreamerBasicType         asjagged(asdtype('>f4'))
Event.ProcessID            TStreamerBasicType         asjagged(asdtype('>i4'))
Event.MPI                  TStreamerBasicType         asjagged(asdtype('>i4'))
Event.Weight               TStreamerBasicType         asjagged(asdtype('>f4'))
Event.CrossSection         TStreamerBasicType         asjagged(asdtype('>f4'))
Event.CrossSectionError    TStreamerBasicType         asjagged(asdtype('>f4'))
Event.Scale                TStreamerBasicType         asjagged(asdtype('>f4'))
Event.AlphaQED             TStreamerBasicType         asjagged

In [89]:
import pandas
file["Delphes"].pandas()


TypeError: 'TTreeMethods_pandas' object is not callable

In [90]:
##histogram almak için deneme yapıyordum ama pandas ı çağırırken sorunla karşılaştım. Buradan itibaren devam edeceğim.